apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.httpUserService.hpa.metadata.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.httpUserService.metadata.name }}
  minReplicas: {{ .Values.httpUserService.hpa.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.httpUserService.hpa.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.httpUserService.hpa.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.httpUserService.hpa.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
