apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.httpUserService.ingress.metadata.name }}
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service: 
            name: http-user-service-svc
            port:
              number: 9091
