apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.httpUserService.deployment.metadata.name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.httpUserService.metadata.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.httpUserService.metadata.name }}
    spec:
      containers:
        - name: {{ .Values.httpUserService.metadata.name }}
          image: {{ .Values.httpUserService.deployment.image.repository }}:{{ .Values.httpUserService.deployment.image.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.httpUserService.deployment.containerPort }}

