{{- if .Values.httpUserService.serviceaccount.metadata.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.httpUserService.serviceaccount.metadata.name }}
automountServiceAccountToken: {{ .Values.httpUserService.serviceaccount.automount }}
{{- end }}
